name: ros2-bridge
on:
  pull_request:
    paths:
      - 'packages/ros2-bridge/**'
  push:
    branches:
      - main
env:
  CI: true
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ros:foxy
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: bootstrap
        run: |
          . /opt/ros/foxy/setup.bash
          npm config set unsafe-perm
          npm ci
        working-directory: .
      - name: lint
        run: npm run lint
      - name: test
        run: . /opt/ros/foxy/setup.bash && npm run test:ci
